title: Xuanrui Hu's Website
description: Personal website showcasing business and projects
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://username.github.io" # Your site URL
markdown: kramdown
theme: minima # Optional, if you're using a theme

# Include directories for assets and projects
include:
  - assets
  - projects

# Exclude files from being processed by Jekyll
exclude: ["node_modules", "Gemfile", "Gemfile.lock"]