# Your site's title
title: "Xuanrui Hu's Development Website"

# If this is hosted under a repo like /shivani-dev or /my-site
url: "https://apozoro.github.io"

# Other basic settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

Here’s a showcase of my UI/UX design work. Click on a project to learn more.

- [Project 1](/Project/Amway)
- [Project 2](/Project/Sunnypaw)
You can explore my design process, wireframes, prototypes, and final designs.


# Collections or sections (Optional, in case you use collections for the business pages)
collections:
  business:
    output: true
